name: diaryminder
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  image_picker: ^1.0.7
  google_mlkit_text_recognition: ^0.11.0
  google_mlkit_commons: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  
  assets:
    - assets/fonts/Jockey_One/
    - assets/images/test.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  
  fonts:
    - family: JockeyOne
      fonts:
        - asset: assets/fonts/Jockey_One/JockeyOne-Regular.ttf
          weight: 400

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
